baseURL = 'https://6bug.org/'
languageCode = 'zh-cn'
title = '六重漏洞'
theme = 'hugo-theme-stack'

DefaultContentLanguage = 'zh-cn'

[params]
sidebar.subtitle = '枕水忧云，一个高中生、oier、程序员和作者'
footer.since = 2025
favicon = '/favicon.ico'

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"
[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "categories"
[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"
[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"

[permalinks]
post = '/p/:slug/'
page = '/:slug/'